language: go

go:
  - 1.13.x

env:
  global:
    - GO111MODULE=on

install:
- go mod download

before_script:
- go vet ./...
- go build ./...
- go test -run xxxx ./...

script:
- go test -race -short -coverprofile=coverage.txt ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build